highcharts/core/urls.py
from django.conf.urls import url
from highcharts.core.graphics import dollar_json, euro_json, product_json
from highcharts.core import views as v

urlpatterns = [
    url(r'^$', v.home, name='home'),
    url(r'^dollar-graphic/$', v.dollar_graphic, name='dollar-graphic'),
    url(r'^euro-graphic/$', v.euro_graphic, name='euro-graphic'),
    url(r'^product-graphic/$', v.product_graphic, name='product-graphic'),
    url(r'^dollar_json/$', dollar_json),
    url(r'^euro_json/$', euro_json),
    url(r'^product_json/$', product_json),
]

highcharts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('highcharts.core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
]

old_project/myproject/urls.py
from django.conf.urls import url
from django.contrib import admin
import myproject.core.views as v

urlpatterns = [
    url(r'^$', v.home, name='home'),
    url(r'^barchart/$', v.barchart, name='barchart'),
    url(r'^columnchart/$', v.columnchart, name='columnchart'),

    url(r'^population/json/$', v.population_list_json, name='population_list_json'),
    url(r'^admin/', admin.site.urls),
]

highcharts/core/models.py
from django.db import models


class Dollar(models.Model):
    date = models.DateField('data')
    value = models.DecimalField('valor', max_digits=4, decimal_places=3)

    class Meta:
        ordering = ['date']
        verbose_name = 'dólar'
        verbose_name_plural = 'dólares'

    def __str__(self):
        return str(self.value)


class Euro(models.Model):
    date = models.DateField('data')
    value = models.DecimalField('valor', max_digits=4, decimal_places=3)

    class Meta:
        ordering = ['date']
        verbose_name = 'euro'
        verbose_name_plural = 'euros'

    def __str__(self):
        return str(self.value)


class Category(models.Model):
    category = models.CharField('categoria', max_length=50, unique=True)

    class Meta:
        ordering = ['category']
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.category


class Product(models.Model):
    category = models.ForeignKey('Category', verbose_name='categoria')
    product = models.CharField('Produto', max_length=60, unique=True)
    price = models.DecimalField('Preço', max_digits=6, decimal_places=2)

    class Meta:
        ordering = ['product']
        verbose_name = 'produto'
        verbose_name_plural = 'produtos'

    def __str__(self):
        return self.product

old_project/myproject/core/models.py
from django.db import models


class Continent(models.Model):
    continent = models.CharField(max_length=30)

    class Meta:
        ordering = ['continent', ]

    def __str__(self):
        return self.continent


class Population(models.Model):
    continent = models.ForeignKey('Continent')
    year = models.PositiveIntegerField()
    population = models.PositiveIntegerField()

    class Meta:
        ordering = ['year', 'continent']

    def __str__(self):
        return "{} {} {}".format(self.continent, self.year, self.population)

highcharts/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'index.html')


def dollar_graphic(request):
    return render(request, 'dollar_graphic.html')


def euro_graphic(request):
    return render(request, 'euro_graphic.html')


def product_graphic(request):
    return render(request, 'product_graphic.html')

old_project/myproject/core/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from itertools import chain
from .models import Continent, Population


def home(request):
    return render(request, 'index.html')


def barchart(request):
    return render(request, 'core/barchart.html')


def columnchart(request):
    return render(request, 'core/columnchart.html')


def population_list_json(request):
    ''' JSON used to generate the graphic '''
    continents = Continent.objects.all()

    pop1800 = Population.objects.all().filter(year='1800')
    pop1900 = Population.objects.all().filter(year='1900')
    pop2008 = Population.objects.all().filter(year='2008')

    context = list(chain(continents, pop1800, pop1900, pop2008))
    s = serializers.serialize("json", context)
    return HttpResponse(s)

highcharts/core/templates/base.html
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <title>Highcharts</title>

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">

  <!-- jQuery -->
  <!-- <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script> -->
  <script src="{% static "js/jquery.min.js" %}"></script>
  <!-- HighCharts JS -->
  <!-- <script src="http://code.highcharts.com/highcharts.js"></script> -->
  <script src="{% static "js/highcharts.js" %}"></script>
  <!-- Bootstrap JS -->
  <script src="{% static "js/bootstrap.min.js" %}"></script>

  <style type="text/css">
    /* Move down content because we have a fixed navbar that is 50px tall */
    body {
      padding-top: 60px;
      padding-bottom: 40px;
      /*color: #5a5a5a;*/
    }
  </style>

</head>
<body>
  {% include "nav.html" %}
  <div class="container">
    {% block content %}{% endblock content %}
    {% block js %}{% endblock js %}
  </div>
</body>
</html>

highcharts/core/templates/dollar_graphic.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div id="dollar-chart"></div>
{% endblock %}

{% block js %}
  <script src="{% static 'js/dollar_graphic.js' %}"></script>
{% endblock js %}

highcharts/core/templates/euro_graphic.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div id="euro-chart"></div>
{% endblock %}

{% block js %}
  <script src="{% static 'js/euro_graphic.js' %}"></script>
{% endblock js %}

highcharts/core/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h2>Highcharts and Django</h2>
        <p>Highcharts and Django test examples.</p>
    </div>
{% endblock content %}

highcharts/core/templates/nav.html
<!-- Menu -->
<div class="navbar navbar navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'core:dollar-graphic' %}">Variação do Dólar</a></li>
        <li><a href="{% url 'core:euro-graphic' %}">Variação do Euro</a></li>
        <li><a href="{% url 'core:product-graphic' %}">Porcentagem de Categorias</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
    </div>
  </div>
</div>

highcharts/core/templates/product_graphic.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div id="product-chart"></div>
{% endblock %}

{% block js %}
  <script src="{% static 'js/product_graphic.js' %}"></script>
{% endblock js %}

old_project/myproject/core/templates/base.html
{% load static %}
<html>
<head>
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Font Awesome core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script src="http://code.jquery.com/jquery-git1.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.js"></script>

    <style type="text/css">
      /* Move down content because we have a fixed navbar that is 50px tall */
      body {
        padding-top: 60px;
        padding-bottom: 40px;
        /*color: #5a5a5a;*/
      }
    </style>

</head>

<body>

{% include "menu.html" %}

<div class="container">

{% block content %}{% endblock content %}

    <!-- Footer -->
    <footer>
        <div class="row clearfix">
            <p><a href="https://github.com/rg3915/highcharts"><span class="fa fa-github"></span> Fork on GitHub</a></p>
        </div>
    </footer>

</div>

{% block js %}{% endblock js %}

</body>
</html>

old_project/myproject/core/templates/core/barchart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div id="container" style="min-width: 310px; max-width: 800px; height: 400px; margin: 0 auto"></div>
{% endblock content %}

{% block js %}
	<script src="{% static 'js/barchart.js' %}"></script>
{% endblock js %}

old_project/myproject/core/templates/core/columnchart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div id="container" style="min-width: 310px; max-width: 800px; height: 400px; margin: 0 auto"></div>
{% endblock content %}

{% block js %}
	<script src="{% static 'js/columnchart.js' %}"></script>
{% endblock js %}

old_project/myproject/core/templates/menu.html
<!-- Menu -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="current"><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="{% url 'barchart' %}"><span class="fa fa-bar-chart"></span> Bar chart</a></li>
        <li><a href="{% url 'columnchart' %}"><span class="fa fa-bar-chart"></span> Column chart</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
    </div>
  </div>
</div>